services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: gtlp_user
      POSTGRES_PASSWORD: gtlp_pass
      POSTGRES_DB: guess_the_last_pokemon
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gtlp_user -d guess_the_last_pokemon"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
